Create Язык самостоятельно.md
ru-de/faq pull request #543
Opened 2020-03-31 15:57 UTC by Nashev

В основном из поста https://t.me/bratwurst/191 натаскал для затравки. Думаю, начинание полезное и надеюсь люди подхватят и накидают ещё ссылок на доступные бесплатные материалы, полезные для изучения Немецкого

2020-04-01 09:03 UTC, okainov commented
На мой взгляд, было бы полезнее, если бы были внятные комментарии, а не просто непонятный набор ссылок. Ну т.е. "заброшенный но полезный" - эээ, ок, а чем полезный-то? А остальные не полезные? Давайте тогда все остальные выкинем, зачем здесь не-полезные ссылки :)
Или "автор проводит эксперименты над собой" - ну кликбейт конечно, но что читатель там найдет? "Популяризация" - популяризация чего вообще? Другие каналы не популяризируют ничего что ли?

Аналогично с телеграм-каналами (или чатами?) - даже с учетом того, что в Телеграме есть определенная проблема с поиском каналов на тему Х, бессвязный набор ссылок не сильно улучшает ситуацию.

См **ровно** такой же комментарий к одному из предыдущих ПР:

>Так я тоже не против ссылок, но ссылки должны **дополнять**, контент а не сами являться контентом. С пояснениями, что за ними и зачем оно нужно. Чем оно **полезно** и **примечательно**. А если пояснения не получается, то и ссылка не нужна.

2020-04-01 09:04 UTC, okainov commented on Язык самостоятельно.md
> +Для самостоятельного изучения языка, в помощь к курсам, существуют следующие доступные бесплатные материалы:
Предлагаю не множить сущности и объединить этот файл с "Языковыми курсами", и переименовать просто в "Язык"

2020-04-01 09:27 UTC, Nashev commented on Язык самостоятельно.md
> +Для самостоятельного изучения языка, в помощь к курсам, существуют следующие доступные бесплатные материалы:
Эта страница может разрастись, а от страницы "язык" я б ожидал не столько ссылки, сколько описание самого языка... Не очень понимаю, как тут относятся к огромным страницам, но обычно они не очень удобны.

2020-04-01 09:28 UTC, Nashev commented on files/dictionary.dic
> +влог
Ну, мне лично более короткое нравится больше, а так - готов пойти поводу у остальных, если их выскажется больше одного, и будет предложено что-то одно конкретное. Ну и потом, потом всегда ж можно поменять...

2020-04-01 09:35 UTC, Nashev commented
На странице с перечнем ссылок - ссылки и есть контент. Если есть желающие дописать пояснений - милости прошу. "но полезный" - чтоб противопоставить тому, что канал заброшен. Хотя, пожалуй, то что канал заброшен тут действительно не очень важно... 

на других каналах - да, не популяризация... 

пояснения приписывал для того, чтоб примерно понимать, что по ссылке, конечно, но и для того, чтоб ссылку в списке узнавать - то есть, как якоря для внимания. С этой целью, кстати, лучше чтоб их было мало и они были не везде.

2020-05-01 23:48 UTC, Dmitry-Borodin commented on Язык самостоятельно.md
> +* [Deutschlandfunk Kultur](https://www.deutschlandfunkkultur.de/) - Статьи с акцентом на таких темах как культура, литература, музыка, наука. На сайте есть также подкасты и радио.
добавил

2020-10-15 22:04 UTC, ewgRa requested changes

2020-10-15 22:04 UTC, ewgRa commented on files/dictionary.dic
> +влог
Я согласен с @okainov. "Влог" читать очень тяжело, я встречал это слово только на некоторых каналах очень развлекательного характера и пока не вижу, чтобы оно вошло в обиход достаточно широко. Я за чистоту речи там где это легко поддерживать.

Вот например к "подкастам" я с трудом подберу альтернативу, разве что аудио-подборки, но тут уже аудио-подборки у всех будут ассоциироваться совсем не с тем что есть подкасты.

```suggestion
```

2020-10-15 22:04 UTC, ewgRa commented on Язык самостоятельно.md
> +* [CrispyRob](https://www.youtube.com/channel/UCvGh4HT9ySBoURt0zSpC0Nw) - развлекательный влог
```suggestion
* [Dima](https://www.youtube.com/channel/UCFMXOlnLLOKl99KV8YfHk-Q) - развлекательный видео-канал
* [CrispyRob](https://www.youtube.com/channel/UCvGh4HT9ySBoURt0zSpC0Nw) - развлекательный видео-канал
```

2020-11-19 17:55 UTC, ewgRa commented
@Nashev merge заблокирован конфликтом, разрешите его пожалуйста.

2021-03-07 08:58 UTC, merged

2021-03-07 08:58 UTC, ewgRa commented
спасибо @Nashev и всем кто учавствовал