Добавлен онлайн способ получения справки из пенсионного
ru-de/faq pull request #550
Opened 2020-05-25 09:46 UTC by felicete

2020-05-26 08:50 UTC, okainov commented
Написал длинный коммент, потом прочитал внимательнее и стер.

Чтобы у других не возникало непоняток, предлагаю дописать что-то вроде "Необходим или телефон с NFC или карт-ридер для eAT". А то в разделе "для компьютера" четко про карт-ридер написано и, не дочитав дальше, это может побудить сразу же закрыть страницу.

2020-05-27 12:56 UTC, felicete commented
Согласна, обновила.

2020-05-27 17:53 UTC, okainov commented
👍

2020-05-31 14:51 UTC, Dmitry-Borodin commented
Какой картридер, зачем? Я получал эту справку две недели назад, просто форму на сайте заполнил и мне письмо пришло.
Заказывал на сайте https://www.eservice-drv.de/SelfServiceWeb/

2020-05-31 14:53 UTC, Dmitry-Borodin commented
Или "получить справку онлайн" имеется в виду, что сама справка будет электронная? Тогда не понятно, как ее можно подавать с остальными документами. Это подписанный pdf?

2020-05-31 17:10 UTC, felicete commented
Не нужен карт-ридер, просто смартфон современный (с NFC), справку сразу скачиваешь, ждать не надо. Она без подписи или печати, но этот способ официально описан на из страницы, так что думаю, она имеет такую же силу, как и реальная бумажная. На ПМЖ с ней еще не успели податься, я отпишусь, как будет результат.

2020-06-01 08:44 UTC, Dmitry-Borodin commented
Я сейчас читаю статью - получилось что получить можно в офисе или онлайн, а потом в отдельной секции что-то про почту.
Видимо что мы хотим сказать, это: 
[*] получить можно на специальный новый телефон установить специальное приложение, чтобы скачать справку сразу
[*] заполнить форму на сайте и получить письмом
[*] сделать термин и сбегать получить онсайт - и это наверное должен быть последний вариант т.к. нафиг не нужен.

Просто раньше это было онсайт и онлайн как две секции. А после редактирования получается, что онлайн - это через приложение, а почта как-то отдельно.

2020-10-15 20:34 UTC, ewgRa requested changes

2020-10-15 20:34 UTC, ewgRa commented on ПМЖ.md
> +  * Справку можно получить онлайн, для этого необходимо иметь сматфон, поддерживающий NFC (чтобы считать eAT-карту) и установить приложение AusweisApp2, подробнее [на сайте DRV (пенсионный фонд)](htt
Я думаю если заменить "онлайн" на "в электронной форме", то это будет более точно отражать смысл. Потому что онлайн это может подразумевать и термин, и заказать по почте, это все онлайн делается. Что думаете об этом?

```suggestion
  * Справку можно получить в электронной форме, для этого необходимо иметь сматфон, поддерживающий NFC (чтобы считать eAT-карту) и установить приложение AusweisApp2, подробнее [на сайте DRV (пенсионный фонд)](https://www.deutsche-rentenversicherung.de/DRV/DE/Online-Dienste/Online-Dienste-mit-Registrierung/online-dienste-mit-registrierung.html) см. раздел Anmeldung mit Smartphone oder Tablet, так как остальные способы подразумевают наличие карт-ридер для eAT-карт.
```

2020-10-17 22:46 UTC, Dmitry-Borodin commented
Сама бумага Wartezeitauskunft называется? Та бумага, что я заказал на сайте, была другая. Там просто выписка взносов, на НЕ не канает.

2020-11-19 18:03 UTC, ewgRa commented
@Dmitry-Borodin я недавно заказывал на сайте у них по ссылке которую ты указал, там можно обе заказать. Versicherungsverlauf и Rentenauskunft :+1:

2020-11-19 18:03 UTC, merged

2020-11-19 18:04 UTC, ewgRa commented
@felicete спасибо