Добавлена ссылка на прием в конс. отдел в Берлине
ru-de/faq pull request #553
Opened 2020-06-06 11:19 UTC by AndreyChirkov

2020-09-25 23:48 UTC, Dmitry-Borodin requested changes

2020-09-25 23:48 UTC, Dmitry-Borodin commented on Консульство.md
> +Процедура довольно простая - идем на сайт генконсульства ([в Мюнхене](https://rusconsmchn.mid.ru)), опционально читаем все детали, потом идем на сайт для заполнения заявления о выдаче загранпаспорта
Идем на сайт консульства в Мюнхене, читаем детали, заполняем поля и записываемся на прием в Берлине !?!?
Очень странное предложение получается. Наверное имеется в виду идем на сайт [в Мюнхене] или [в Брелине]

2020-10-15 20:22 UTC, ewgRa requested changes

2020-10-15 20:22 UTC, ewgRa commented on Консульство.md
> +Процедура довольно простая - идем на сайт генконсульства ([в Мюнхене](https://rusconsmchn.mid.ru)), опционально читаем все детали, потом идем на сайт для заполнения заявления о выдаче загранпаспорта
Я бы сделал как Дмитрий предложил: просто рядом с ([в Мюнхене](https://rusconsmchn.mid.ru)) добавить такую же ссылку для Берлина https://russische-botschaft.ru/ru/ и наверное все на этом.

Но в целом это гуглиться на раз два, и ссылки там все есть на страницах (например запись на прием есть на https://russische-botschaft.ru/ru/consulate/konsulskijj-otdel/), и информации гораздо больше о правилах посещения и т.п.

2020-11-19 17:59 UTC, ewgRa commented
закрываю пока за давностью и отсутствию движения

@AndreyChirkov спасибо за PR, предложил здесь корректировку: https://github.com/ru-de/faq/pull/553#discussion_r505815749

Если будет желание и возможность - либо переоткрыть этот PR и внести корректировку, или создать новый.

2020-11-19 17:59 UTC, closed without merging