Обновил порядок замены прав (сдачи теоретического экзамена)
ru-de/faq pull request #566
Opened 2020-10-13 12:44 UTC by uzzz

Записывать на теоретический экзамен больше не нужно

2020-10-13 17:36 UTC, okainov commented on Авто.md
> +- Оплачиваете теоретический эзамен, ждете 5 дней пока платеж дойдет до них
До кого "до них"? Было бы неплохо добавить ссылку

2020-10-14 08:11 UTC, uzzz commented on Авто.md
> +- Приходите и в любой день проходите экзамен (с 25.05.2020 отменили предварительную запись на теоретический экзамен)
Хороший поинт. Я говорил про Берлин и DEKRA, вот пруф - https://www.dekra.de/berlin-tempelhof/kontakt/oeffnungszeiten.html (`Theory exams: from 25th of May 2020 onward without any appointment`)

Тоько пока не понял - это только к Берлину относится, или в других местах тоже так.

2020-10-14 12:34 UTC, okainov commented on Авто.md
> +- Приходите и в любой день проходите экзамен (с 25.05.2020 отменили предварительную запись на теоретический экзамен)
Вот и допишите это в текст :)

2020-10-15 19:57 UTC, ewgRa requested changes

2020-10-15 19:57 UTC, ewgRa commented on Авто.md
> +- Приходите и в любой день проходите экзамен (с 25.05.2020 отменили предварительную запись на теоретический экзамен)
Я предлагаю откатить это изменение. Это только Dekra такое сделала, и не факт, что потом не вернет обратно. Лучше исходить из принципа наименьшего ущерба. Лучше человек попытается записаться на прием и не найдет как это делать, чем придет без записи и его отправят домой в расстроеных чувствах.

Например TUV https://www.tuev-nord.de/de/privatkunden/verkehr/fuehrerschein/theoretische-pruefung/, у них судя по всему по записи.

2020-10-15 19:57 UTC, ewgRa commented on Авто.md
> +- Ждете 1-6 недель, подтверждение придет по почте
Можно какой-нибудь заголовок из этих писем, чтобы попробовать поискать дополнительную информацию? Потому что например TUV может и не присылать. Непонятно - это все сейчас так будут делать, или только Dekra.

2020-11-21 21:21 UTC, ewgRa commented
закрываю за давностью, множества вопросов и отсутствию движения

спасибо @uzzz, пока слишком непонятно, судя по всему единого алгоритма пока что нету и очень зависит все от школы и где сдавать в TUV или Dekra.

2020-11-21 21:21 UTC, closed without merging