auto sharenow miles
ru-de/faq pull request #619
Opened 2021-07-29 21:11 UTC by sergentum

Спасибо, что решили помочь проекту и внести свой вклад в его развитие.

Нам очень поможет, если перед созданием Pull Request вы ознакомитесь с содержимым файла CONTRIBUTING.md, где перечислено:
- какая информация приветствуется;
- какая информация не соответствует формату данного ресурса;
- как оформить Pull Request;
- что ожидать после создания Pull Request.

2021-08-09 18:36 UTC, ewgRa requested changes

2021-08-09 18:36 UTC, ewgRa commented on Авто.md
> +### ShareNow
Я бы убрал вообще их если по новым информации не добавляется, а старая информация неактуальна больше.
Мне кажется нет смысла сохранять устаревшую информацию.

2021-08-09 19:53 UTC, sergentum commented on Авто.md
> +### ShareNow
согласен, удалил

2021-09-07 19:56 UTC, merged

2021-09-07 19:56 UTC, ewgRa commented
спасибо @sergentum